# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the packaged jar file into the container
COPY target/invoice-system.jar invoice-system.jar

# Run the jar file
ENTRYPOINT ["java", "-jar", "invoice-system.jar"]
